# Generated by Django 5.1.7 on 2025-08-03 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='allow_multiple_languages',
            field=models.BooleanField(default=True, help_text='Allow multiple programming languages'),
        ),
        migrations.AddField(
            model_name='problem',
            name='cpu_time_limit',
            field=models.IntegerField(default=1000, help_text='CPU time limit in milliseconds'),
        ),
        migrations.AddField(
            model_name='problem',
            name='default_language_id',
            field=models.IntegerField(default=54, help_text='Default Judge0 language ID (54 = Python3)'),
        ),
        migrations.AddField(
            model_name='problem',
            name='enable_network',
            field=models.BooleanField(default=False, help_text='Enable network access'),
        ),
        migrations.AddField(
            model_name='problem',
            name='max_submissions',
            field=models.IntegerField(default=10, help_text='Maximum submissions allowed per user'),
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=512000, help_text='Memory limit in bytes'),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=1000, help_text='Time limit in milliseconds'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.IntegerField(help_text='Judge0 language ID')),
                ('source_code', models.TextField(help_text="User's source code")),
                ('stdin', models.TextField(blank=True, help_text='Input data for testing')),
                ('expected_output', models.TextField(blank=True, help_text='Expected output for comparison')),
                ('judge0_token', models.CharField(blank=True, help_text='Judge0 submission token', max_length=100)),
                ('status', models.CharField(choices=[('In Queue', 'In Queue'), ('Processing', 'Processing'), ('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Memory Limit Exceeded', 'Memory Limit Exceeded'), ('Runtime Error', 'Runtime Error'), ('Compilation Error', 'Compilation Error'), ('Internal Error', 'Internal Error')], default='In Queue', max_length=50)),
                ('stdout', models.TextField(blank=True, help_text='Program output')),
                ('stderr', models.TextField(blank=True, help_text='Error output')),
                ('compile_output', models.TextField(blank=True, help_text='Compilation output')),
                ('time', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('memory', models.IntegerField(blank=True, help_text='Memory used in bytes', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contest.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Test case name/description', max_length=100)),
                ('input_data', models.TextField(help_text='Input data for the test case')),
                ('expected_output', models.TextField(help_text='Expected output (hidden from users)')),
                ('is_sample', models.BooleanField(default=False, help_text='Whether this is a sample test case shown to users')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this test case is visible to users')),
                ('order', models.IntegerField(default=0, help_text='Order of test case display')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='contest.problem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
