# Generated by Django 5.1.7 on 2025-09-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_problem_allow_multiple_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='cpu_time_limit',
            field=models.IntegerField(default=2000, help_text='CPU time limit in milliseconds'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=128000, help_text='Memory limit in bytes'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=2000, help_text='Time limit in milliseconds'),
        ),
    ]
