# Generated by Django 5.1.7 on 2025-09-09 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_alter_problem_cpu_time_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code_similarity_score',
            field=models.FloatField(blank=True, help_text='Similarity score with other submissions', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='copy_paste_events',
            field=models.IntegerField(default=0, help_text='Number of copy-paste events detected'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text="User's IP address", null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='keystrokes_count',
            field=models.IntegerField(blank=True, help_text='Number of keystrokes', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='session_id',
            field=models.CharField(blank=True, help_text='User session identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='tab_switches',
            field=models.IntegerField(default=0, help_text='Number of tab switches during coding'),
        ),
        migrations.AddField(
            model_name='submission',
            name='time_spent_coding',
            field=models.IntegerField(blank=True, help_text='Time spent coding in seconds', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='user_agent',
            field=models.TextField(blank=True, help_text="User's browser/client information"),
        ),
        migrations.CreateModel(
            name='PlagiarismCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='Similarity percentage (0-100)')),
                ('algorithm_used', models.CharField(default='levenshtein', help_text='Algorithm used for comparison', max_length=50)),
                ('details', models.JSONField(default=dict, help_text='Detailed comparison results')),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False, help_text='Whether this has been reviewed by admin')),
                ('submission1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_checks_as_first', to='contest.submission')),
                ('submission2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_checks_as_second', to='contest.submission')),
            ],
            options={
                'ordering': ['-similarity_score', '-flagged_at'],
                'unique_together': {('submission1', 'submission2')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('total_time_spent', models.IntegerField(default=0, help_text='Total time in seconds')),
                ('code_changes', models.JSONField(default=list, help_text='History of code changes')),
                ('keystroke_patterns', models.JSONField(default=dict, help_text='Keystroke timing patterns')),
                ('mouse_movements', models.IntegerField(default=0, help_text='Mouse movement count')),
                ('idle_time', models.IntegerField(default=0, help_text='Total idle time in seconds')),
                ('suspicious_activities', models.JSONField(default=list, help_text='List of suspicious activities')),
                ('browser_focus_lost', models.IntegerField(default=0, help_text='Times browser lost focus')),
                ('copy_paste_attempts', models.IntegerField(default=0, help_text='Copy-paste attempts')),
                ('external_resource_access', models.JSONField(default=list, help_text='External resources accessed')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='contest.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('user', 'problem', 'session_id')},
            },
        ),
    ]
