# Generated by Django 5.1.7 on 2025-09-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_submission_code_similarity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text="User's IP address", null=True),
        ),
    ]
