# Generated by Django 5.1.7 on 2025-09-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_useractivity_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='contest',
            name='departments',
            field=models.JSONField(blank=True, default=list, help_text='List of departments that can access this contest', null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='share_enabled',
            field=models.BooleanField(default=False, help_text='Whether the contest can be shared publicly'),
        ),
        migrations.AddField(
            model_name='contest',
            name='share_link',
            field=models.CharField(blank=True, help_text='Public link that can be shared if sharing is enabled', max_length=255, null=True),
        ),
    ]
